### ISSUE TITLE
Feeding Frenzy

### ISSUE THREAD

**Issue by MrMIST3R** [itsmeow/betteranimalsplus#127]
I was searching for pet feral wolves and found some coyotes along the way and tamed them. Finally caught some and tamed them. One of them got hurt so i fed it and my game crashed. Relogged only to see them scooting around in the sitting positon and feeding them only cause the game to crash again. Used rotten meat as food.

**To Reproduce** (Required unless unknown)
Steps to reproduce the behavior (if possible):
1. tame feral wolf or coyote
2. feed it food or just rotten flesh idk
3. game crashes
[crash-2019-12-29_20.33.55-client.txt](https://github.com/itsmeow/betteranimalsplus/files/4008793/crash-2019-12-29_20.33.55-client.txt)

**Crash Log (REQUIRED)**
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/29/19 8:33 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$3(LogicalSidedProvider.java:33) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.LogicalSidedProvider$$Lambda$2028/935813802.apply(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.PacketDistributor.getServer(PacketDistributor.java:263) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.PacketDistributor.lambda$playerListAll$3(PacketDistributor.java:223) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.PacketDistributor$$Lambda$3710/1943888330.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.PacketDistributor$PacketTarget.send(PacketDistributor.java:178) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.send(SimpleChannel.java:118) ~[?:?] {re:classloading}
	at fr.zeamateis.damage_indicator.amy.network.AmyNetwork.sendPacketToEveryone(AmyNetwork.java:31) ~[?:0.0.7] {re:classloading}
	at fr.zeamateis.damage_indicator.common.event.CommonEventHandler.onLivingHeal(CommonEventHandler.java:61) ~[?:0.0.7] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_17_CommonEventHandler_onLivingHeal_LivingHealEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onLivingHeal(ForgeEventFactory.java:491) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70691_i(LivingEntity.java:828) ~[?:?] {re:classloading}
	at its_meow.betteranimalsplus.common.entity.EntityCoyote.func_184645_a(EntityCoyote.java:140) ~[?:8.1.0] {re:classloading}
	at net.minecraft.entity.MobEntity.func_184230_a(MobEntity.java:1380) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:959) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.PlayerController.func_187097_a(PlayerController.java:352) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_187097_a(PlayerControllerOF.java:113) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1488) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1321) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.108.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$418/425275537.call(Unknown Source) [forge-1.14.4-28.1.108.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$3(LogicalSidedProvider.java:33)
	at net.minecraftforge.fml.LogicalSidedProvider$$Lambda$2028/935813802.apply(Unknown Source)
	at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60)
	at net.minecraftforge.fml.network.PacketDistributor.getServer(PacketDistributor.java:263)
	at net.minecraftforge.fml.network.PacketDistributor.lambda$playerListAll$3(PacketDistributor.java:223)
	at net.minecraftforge.fml.network.PacketDistributor$$Lambda$3710/1943888330.accept(Unknown Source)
	at net.minecraftforge.fml.network.PacketDistributor$PacketTarget.send(PacketDistributor.java:178)
	at net.minecraftforge.fml.network.simple.SimpleChannel.send(SimpleChannel.java:118)
	at fr.zeamateis.damage_indicator.amy.network.AmyNetwork.sendPacketToEveryone(AmyNetwork.java:31)
	at fr.zeamateis.damage_indicator.common.event.CommonEventHandler.onLivingHeal(CommonEventHandler.java:61)
	at net.minecraftforge.eventbus.ASMEventHandler_17_CommonEventHandler_onLivingHeal_LivingHealEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.onLivingHeal(ForgeEventFactory.java:491)
	at net.minecraft.entity.LivingEntity.func_70691_i(LivingEntity.java:828)
	at its_meow.betteranimalsplus.common.entity.EntityCoyote.func_184645_a(EntityCoyote.java:140)
	at net.minecraft.entity.MobEntity.func_184230_a(MobEntity.java:1380)
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:959)
	at net.minecraft.client.multiplayer.PlayerController.func_187097_a(PlayerController.java:352)
	at net.optifine.override.PlayerControllerOF.func_187097_a(PlayerControllerOF.java:113)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1229)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1488)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['NCTrinity'/277374, l='MpServer', x=95.65, y=67.00, z=-1350.00]]
	Chunk stats: Client Chunk Cache: 729, 698
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (240,65,128), Chunk: (at 0,4,0 in 15,8; contains blocks 240,0,128 to 255,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 52815549 game time, 53913435 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$418/425275537.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 914030048 bytes (871 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.108.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.108.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.108.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.108.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.108
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		forge-1.14.4-28.1.108-client.jar Minecraft {minecraft@1.14.4 DONE}
		DungeonCrawl-1.14.4-1.4.0.jar Dungeon Crawl {dungeoncrawl@1.4.0 DONE}
		betteranimalsplus-1.14.4-8.1.0.jar Better Animals Plus {betteranimalsplus@8.1.0 DONE}
		Ring-of-Teleport-Mod-1.14.4.jar Ring of Teleport {ring_of_teleport@1.0.7 DONE}
		damage_indicator-0.0.7.jar Ama's Damage Indicator {damage_indicator@0.0.7 DONE}
		Morpheus-Mod-1.14.4.jar Morpheus {morpheus@version DONE}
		jei-1.14.4-6.0.0.10.jar Just Enough Items {jei@6.0.0.10 DONE}
		extcaves-1.4.2.jar Extended Caves {extcaves@1.4.2 DONE}
		VoxelMap-Mod-1.14.4.jar VoxelMap {voxelmap@1.9.13 DONE}
		forge-1.14.4-28.1.108-universal.jar Forge {forge@28.1.108 DONE}
		extraboats-1.1.2-1.14.4.jar Extra Boats {extraboats@1.1.2 DONE}
		SuperTools-1.14.4.jar Super Tools {supertools@1.2c DONE}
		Recycler-Mod-1.14.4.jar Recycler {recycler@1.0.0 DONE}
		extlights-1.7.jar Extended Lights {extlights@1.7 DONE}
		enchxchg-1.14.4-5.0.0.jar Enchantments Exchanger {enchxchg@1.14.4-5.0.0 DONE}
		StorageDrawers-1.14.4-6.0.2.jar Storage Drawers {storagedrawers@1.14.4-6.0.1 DONE}
	Launched Version: 1.14.4-forge-28.1.108
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) UHD Graphics 630 GL version 4.5.0 - Build 25.20.100.6446, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 25.20.100.6446
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Versions:**
 - Forge Version: 28.1.108
 - MC Version: 1.14.4
 - Mod Version: 8.1.0

**Additional context**
also would be cool if the tamed pets also instant transmissioned with me when i use my teleport ring mod

**Comment by itsmeow** [comment]
This is caused by Damage Indicator https://github.com/JibayMcs/Ama-s-Damage-Indicator/issues/1 and https://github.com/JibayMcs/Ama-s-Damage-Indicator/issues/2
There is nothing I can do to fix this and unfortunately it seems as though @JibayMcs has neglected to fix it for a month or two now

**Comment by MrMIST3R** [comment]
SO replaced that damage indicator for NEAT and no more crashing BUT anytime i tame an animal and close my game and come back they are stuck in a sitting position, they dont follow me they just scoot on their bums willy nilly
