### ISSUE TITLE
"Exception generating new chunk" in 1.15.2 alpha version

### ISSUE THREAD

**Issue by QuantumToasted** [itsmeow/betteranimalsplus#149]
**Describe what you were doing before the crash**

Flying around in spectator mode to explore my server, then suddently disconnected with the message "Server closed" (unrelated, but that was exactly what happened).

**To Reproduce**
I can't guarantee that this would reproduce it but possibly a server with the same mods and world seed, then teleporting to where I was when the crash occurred?

**Crash Log (REQUIRED)**
<details><summary>Crash Log</summary>
<p>

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 3/5/20 5:22 PM
Description: Exception generating new chunk

java.lang.ClassCastException: its_meow.betteranimalsplus.common.entity.IVariantTypes$TypeData cannot be cast to net.minecraft.entity.AgeableEntity$AgeableData
	at net.minecraft.entity.AgeableEntity.func_213386_a(SourceFile:41) ~[?:?] {re:classloading}
	at its_meow.betteranimalsplus.common.entity.EntityReindeer.func_213386_a(EntityReindeer.java:1010) ~[?:8.2.1.13] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:263) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.OverworldChunkGenerator.func_202093_c(SourceFile:56) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:86) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:237) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:519) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:517) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_241] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.AgeableEntity.func_213386_a(SourceFile:41)
	at its_meow.betteranimalsplus.common.entity.EntityReindeer.func_213386_a(EntityReindeer.java:1010)
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:263)
	at net.minecraft.world.gen.OverworldChunkGenerator.func_202093_c(SourceFile:56)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:86)
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:237)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195)

-- Chunk to be generated --
Details:
	Location: -142,-179
	Position hash: -764504178830
	Generator: biomesoplenty.common.world.ChunkGeneratorOverworldBOP@267ea88d
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:519)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:517)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['FashAnimeGirl'/154, l='world', x=-2442.18, y=81.10, z=-2790.08]]
	Chunk stats: ServerChunkCache: 4047
	Level dimension: DimensionType{minecraft:overworld}
	Level name: world
	Level seed: -1410814865
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-240,63,-236), Chunk: (at 0,3,4 in -15,-15; contains blocks -240,0,-240 to -225,255,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 18914 game time, 6875 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 156545 (now: false), thunder time: 40923 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:329)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2851782920 bytes (2719 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 6
	JVM Flags: 12 total; -Xms8G -Xmx8G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.18
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.18-server.jar Minecraft {minecraft@1.15.2 DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		tubesreloaded-1.15.2-1.3.0b.jar Tubes Reloaded {tubesreloaded@1.15.2-1.3.0b DONE}
		tombstone-4.2.4-1.15.2.jar Corail Tombstone {tombstone@4.2.4 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		betteranimalsplus-1.15.2-8.2.1.13.jar Better Animals Plus {betteranimalsplus@8.2.1.13 DONE}
		Ping-1.15.2-1.6.4.jar Ping {ping@1.15.2-1.6.4 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 DONE}
		EquipmentTooltips-1.15.2-1.4.0+11.jar Equipment Tooltips {equipmenttooltips@1.4.0+11 DONE}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Morpheus-1.15.2-4.2.47.jar Morpheus {morpheus@version DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		tramplestopper-1.15.2-2.0.0.beta-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.beta-universal DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		forge-1.15.2-31.1.18-universal.jar Forge {forge@31.1.18 DONE}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
	Player Count: 1 / 50; [ServerPlayerEntity['FashAnimeGirl'/154, l='world', x=-2442.18, y=81.10, z=-2790.08]]
	Data Packs: vanilla, mod:appleskin (incompatible), mod:betteranimalsplus (incompatible), mod:biomesoplenty, mod:doggytalents (incompatible), mod:dungeoncrawl (incompatible), mod:elevatorid, mod:equipmenttooltips (incompatible), mod:fastleafdecay, mod:forge (incompatible), mod:morpheus (incompatible), mod:ping, mod:randompatches (incompatible), mod:storagedrawers (incompatible), mod:tombstone, mod:tramplestopper (incompatible), mod:trashslot (incompatible), mod:tubesreloaded (incompatible), mod:waila (incompatible), mod:xlfoodmod
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

</p>
</details>

**Versions:**
 - OS: Windows 10 x64
 - MC Version: 1.15.2, Forge `forge-1.15.2-31.1.18.jar`
 - Mod Version: `betteranimalsplus-1.15.2-8.2.1.13.jar`

**Additional Info**
If it matters, this continues to happen every time I restart the server and log back on.

**Comment by itsmeow** [comment]
1.15 is not supported currently
