### ISSUE TITLE
Crashes anytime you try and tame an animal

### ISSUE THREAD

**Issue by AngelDog626** [itsmeow/betteranimalsplus#199]
Everything spawns and works fine on the server but I went to tame a wild coyote and the game crashes along with my server. Has this been an issue for everyone? (sorry I've got several mods so my crash log is probably a little wordy)

**Crash Log (REQUIRED)**
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 9/11/20 7:36 PM
Description: mouseDragged event handler

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51] {}
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51] {}
	at journeymap.client.ui.component.ScrollListPane.getSlot(ScrollListPane.java:197) ~[?:1.15.2-5.7.0b2] {re:classloading}
	at journeymap.client.ui.component.ScrollListPane.mouseDragged(ScrollListPane.java:184) ~[?:1.15.2-5.7.0b2] {re:classloading}
	at journeymap.client.ui.waypoint.WaypointManager.mouseDragged(WaypointManager.java:334) ~[?:1.15.2-5.7.0b2] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$cursorPosCallback$9(MouseHelper.java:192) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$5149/1757829187.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198022_b(MouseHelper.java:190) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$2(MouseHelper.java:159) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4430/798418079.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$3(MouseHelper.java:158) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3662/1507820612.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:375) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:946) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.31.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/1787987889.call(Unknown Source) [forge-1.15.2-31.2.31.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at journeymap.client.ui.component.ScrollListPane.getSlot(ScrollListPane.java:197)
	at journeymap.client.ui.component.ScrollListPane.mouseDragged(ScrollListPane.java:184)
	at journeymap.client.ui.waypoint.WaypointManager.mouseDragged(WaypointManager.java:334)
	at net.minecraft.client.MouseHelper.lambda$cursorPosCallback$9(MouseHelper.java:192)
	at net.minecraft.client.MouseHelper$$Lambda$5149/1757829187.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: journeymap.client.ui.waypoint.WaypointManager
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198022_b(MouseHelper.java:190)
	at net.minecraft.client.MouseHelper.lambda$null$2(MouseHelper.java:159)
	at net.minecraft.client.MouseHelper$$Lambda$4430/798418079.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$3(MouseHelper.java:158)
	at net.minecraft.client.MouseHelper$$Lambda$3662/1507820612.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['AngelDog626'/55, l='MpServer', x=-320.31, y=73.53, z=-4.52]]
	Chunk stats: Client Chunk Cache: 289, 145
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -1337503246826345627
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-208,63,-55), Chunk: (at 0,3,9 in -13,-4; contains blocks -208,0,-64 to -193,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 3729 game time, 3729 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/1787987889.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 977332256 bytes (932 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine%201.15.2%20HD_U_G9.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.31.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.31
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.31-client.jar Minecraft {minecraft@1.15.2 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		luckyblock-1.15.2-1.jar Lucky Block {lucky@1.15.2-1 DONE}
		EndReborn+[0.6.0].jar End: Reborn {endreborn@0.6.0 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		mcws-roofs-1.15.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		cfm-7.0.0-pre16-mc1.15.1(1).jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 DONE}
		Aquaculture-1.15.2-2.0.16.jar Aquaculture 2 {aquaculture@1.15.2-2.0.16 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		citadel-1.1.11.jar Citadel {citadel@1.1.11 DONE}
		iceandfire-2.0.0.jar Ice and Fire {iceandfire@2.0.0 DONE}
		rats-5.3.2-1.15.2.jar Rats {rats@5.3.2 DONE}
	Launched Version: 1.15.2-forge-31.2.31
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 630 GL version 4.4.0 - Build 22.20.16.4708, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre16
	OptiFine Build: 20200506-004910
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 22.20.16.4708
	OpenGlRenderer: Intel(R) HD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 8

**Versions:**
 - Minecraft Version:
 - Forge Version:
 - Mod Version:

**Additional context**

**Comment by itsmeow** [comment]
This is a crash log for JourneyMap.

**Comment by ThePoshTux** [comment]
Unfortunately I can't provide a better log for this one other than this usable excerpt, but it is the same issue of the taming the coyote causing the crash. Angel dog may have given a concise crash log that removed what it though was irrelevant log info.

 `[20Sep2020 20:06:23.425] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: its_meow.betteranimalsplus.common.entity.EntityCoyote.func_70908_e(Z)V
	at its_meow.betteranimalsplus.common.entity.EntityCoyote.func_184645_a(EntityCoyote.java:181) ~[?:8.2.1.96]
	at net.minecraft.entity.MobEntity.func_184230_a(MobEntity.java:953) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:985) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1067) ~[?:?]
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:68) ~[?:?]
	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]`

**Comment by itsmeow** [comment]
Duplicate of #174
