### ISSUE TITLE
Geese crashing server

### ISSUE THREAD

**Issue by ghost** [itsmeow/betteranimalsplus#207]
Flying around

**To Reproduce**
1. I was just flying around existing chunks. It seems that when it tries to spawn or load a goose, it crashes the server. And the server will crash if I spam throw the goose egg. This message appears at crash, and it will also appear if I use the "spawn goose" egg, although not crash.

**Crash Log (REQUIRED)**
[10:07:43] [Server thread/ERROR] [FML]: Encountered an exception while constructing entity 'betteranimalsplus:goose'
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_191]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:305) [EntityEntryBuilder$ConstructorFactory.class:git-HEAD-a8543ec]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:291) [EntityEntryBuilder$ConstructorFactory.class:git-HEAD-a8543ec]
	at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:68) [EntityEntry.class:git-HEAD-a8543ec]
	at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:657) [anh$c.class:?]
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:164) [anb.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:399) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:896) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:464) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:786) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:667) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: its_meow.betteranimalsplus.common.entity.EntityGoose.func_98053_h(Z)V
	at its_meow.betteranimalsplus.common.entity.EntityGoose.<init>(EntityGoose.java:75) ~[EntityGoose.class:9.0.1]
	... 15 more
[10:07:43] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:901) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:464) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:786) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:667) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:172) ~[anb.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:399) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:896) ~[MinecraftServer.class:?]
	... 4 more

**Versions:**
 - Minecraft Version: 1.12.2
 - Forge Version:  forge-1.12.2-14.23.5.2854
 - Mod Version: 1.12.2-9.0.1

**Additional context**
This doesn't seem to happen with any other mob. They all spawn fine.

**Comment by itsmeow** [comment]
Can you include your full game log prior to the crash? This is lacking information in the log.

**Comment by itsmeow** [comment]
I am led to believe you have some sort of coremod that is interfering with the mod and causing this issue

**Comment by itsmeow** [comment]
Closing due to inactivity and no further information that implies anything other than coremod interference.
