### ISSUE TITLE
loading into singleplayer world stuck at 100%

### ISSUE THREAD

**Issue by Andrezinho1** [itsmeow/betteranimalsplus#208]
[17:32:28] [Server thread/WARN]: defineId called for: class its_meow.betteranimalsplus.common.entity.EntityGoose from class dev.itsmeow.betteranimalsplus.imdlib.entity.util.EntityTypeContainer
[17:32:28] [Server thread/ERROR]: Exception caught during firing event: null
	Index: 24
	Listeners:
		0: HIGHEST
		1: ASM: mcjty.incontrol.ForgeEventHandlers@7cfd8aa onEntityJoinWorldLast(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		2: ASM: net.minecraftforge.common.ForgeInternalHandler@3f82acca onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		3: NORMAL
		4: ASM: shadows.fastbench.FastBench@1093c367 normalRemoval(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		5: ASM: shadows.fastbench.FastBench@1093c367 playerContainerStuff(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		6: ASM: com.github.alexthe666.citadel.server.CitadelServerEvents@973c7cd onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		7: ASM: shadows.apotheosis.deadly.loot.affix.AffixEvents@3192730 onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		8: ASM: class shadows.wstweaks.WSTEvents join(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		9: ASM: class info.u_team.u_team_core.intern.event.UpdateDiscordEventHandler on(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		10: ASM: class com.lazy.baubles.event.EventHandlerEntity playerJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		11: ASM: class com.commodorethrawn.strawgolem.events.IronGolemHandler ironGolemSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		12: ASM: class com.commodorethrawn.strawgolem.events.GolemEventHandler playerJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		13: net.minecraftforge.eventbus.EventBus$$Lambda$2105/1833703608@df50165
		14: ASM: class com.github.klikli_dev.occultism.handlers.CapabilityEventHandler onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		15: ASM: com.legacy.mining_helmet.MiningHelmetEvents@717ca354 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		16: ASM: everlastingabilities onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		17: ASM: net.yezon.theabyss.procedures.INFOMESSAGEProcedure@5da60c63 onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		18: ASM: net.mcreator.refreshed_nether.procedures.FskeletonpillagerewrProcedure@5df8cea3 onEntitySpawned(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		19: ASM: class com.oblivioussp.spartanweaponry.event.CommonEventHandler onJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		20: ASM: class me.ichun.mods.backtools.client.core.EventHandler onItemSpawnEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		21: ASM: com.blackgear.nether.common.events.NetheriteResistanceEvent@506ccde9 itemDropped(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		22: ASM: class com.builtbroken.ai.improvements.modifier.ModifierSystem onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		23: ASM: atomicstryker.infernalmobs.client.InfernalMobsClient@55edf56d onEntityJoinedWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		24: ASM: atomicstryker.infernalmobs.common.EntityEventHandler@3a37997d onEntityJoinedWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		25: net.minecraftforge.eventbus.EventBus$$Lambda$2105/1833703608@a3debb3
		26: net.minecraftforge.eventbus.EventBus$$Lambda$2105/1833703608@1a504f46
		27: ASM: pam.pamhc2crops.events.TemptationTask@160187d2 onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		28: ASM: io.github.strikerrocker.vt.world.SelfPlanting@7fe1ed1b itemToss(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		29: ASM: vazkii.quark.automation.module.ChainLinkageModule@18b3ac25 onVehicleArrive(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		30: ASM: vazkii.quark.automation.module.FeedingTroughModule@45143eca onOrbSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		31: ASM: vazkii.quark.building.module.VariantChestsModule@771da2d8 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		32: ASM: svenhjol.charm.enchanting.module.Magnetic@523ef14b onEntityCreate(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		33: ASM: svenhjol.charm.tweaks.module.RemoveNitwits@2f0a5827 onVillagerSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		34: ASM: vazkii.quark.tweaks.module.PatTheDogsModule@2e841741 onWolfAppear(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		35: ASM: vazkii.quark.tweaks.module.VillagersFollowEmeraldsModule@101791f8 onVillagerAppear(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		36: ASM: svenhjol.charm.world.module.MoreVillageBiomes@1f74862f onVillagerSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		37: net.minecraftforge.eventbus.EventBus$$Lambda$2105/1833703608@53330adb
		38: ASM: com.pam.pamhc2trees.events.TemptationTask@74432507 onEntitySpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		39: ASM: top.theillusivec4.curios.common.event.EventHandlerCurios@66d577b1 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		40: LOWEST
		41: ASM: class com.teamabnormals.upgrade_aquatic.core.events.EntityEvents onEntitySpawned(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		42: ASM: mcjty.incontrol.ForgeEventHandlers@7cfd8aa onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
java.lang.NullPointerException
	at atomicstryker.infernalmobs.common.InfernalMobsCore.stringToMobModifiers(InfernalMobsCore.java:487)
	at atomicstryker.infernalmobs.common.InfernalMobsCore.addEntityModifiersByString(InfernalMobsCore.java:468)
	at atomicstryker.infernalmobs.common.EntityEventHandler.onEntityJoinedWorld(EntityEventHandler.java:36)
	at net.minecraftforge.eventbus.ASMEventHandler_993_EntityEventHandler_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:912)
	at net.minecraft.world.server.ChunkManager.lambda$null$25(ChunkManager.java:586)
	at net.minecraft.world.server.ChunkManager$$Lambda$14327/1599807371.apply(Unknown Source)
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
	at com.mojang.datafixers.util.Either$$Lambda$14328/183958412.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$26(ChunkManager.java:563)
	at net.minecraft.world.server.ChunkManager$$Lambda$14324/1266933611.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$14251/1680158743.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(SourceFile:551)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:560)
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:278)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:719)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694)
	at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:467)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:83)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613)
	at java.lang.Thread.run(Thread.java:745)

I think it's something to do with the goose

**Comment by Andrezinho1** [comment]
**Version**
minecraft:1.15.2
forge-31.2.45

**Comment by itsmeow** [comment]
This crash is caused by infernal mobs. The WARN line above the log is entirely coincidental and not something to worry about.
