### ISSUE TITLE
Trouble at start 

### ISSUE THREAD

**Issue by Rothusar** [itsmeow/betteranimalsplus#227]
**Describe what you were doing before the crash**
[eg. Loading game, creating world, spawning a certain mob, hurting a mob, walking around]

**To Reproduce**
Steps to reproduce the behavior (if possible):
1. Spawn '...'
3. See error

**Crash Log (REQUIRED)**
Get your minecraft crash log and paste it here.

[29Dez2020 10:58:40.833] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: betteranimalsplus, class its_meow.betteranimalsplus.BetterAnimalsPlusMod
java.lang.NoSuchMethodError: net.minecraftforge.registries.DeferredRegister.create(Lnet/minecraftforge/registries/IForgeRegistry;Ljava/lang/String;)Lnet/minecraftforge/registries/DeferredRegister;
	at its_meow.betteranimalsplus.init.ModBlocks.<clinit>(ModBlocks.java:18) ~[?:10.1.0]
	at its_meow.betteranimalsplus.BetterAnimalsPlusMod.<init>(BetterAnimalsPlusMod.java:77) ~[?:10.1.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:31.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2180/498833994.accept(Unknown Source) [?:31.1]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2179/305638003.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2179/305638003.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2250/199126858.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]

**Versions:**
 - Minecraft Version:
 - Forge Version: 31.1.0
 - Mod Version: 10.1.0

**Additional context**

**Comment by itsmeow** [comment]
You are running Forge for 1.16.2. You need to update to Forge for 1.16.4.
