### ISSUE TITLE
Failed to remove serverconfig from tracker!

### ISSUE THREAD

**Issue by paulhlschr** [itsmeow/betteranimalsplus#234]
**Describe the bug**
After stopping the server, the serverconfig file betteranimalsplus-server.toml fails to get removed from tracker. As a result the server process is not stopped successfully. On UNIX systems the server process even runs still after Ctrl-C the console manually.

**To Reproduce**
1. Download [Verve 2 1.2.2 Server Pack](https://www.curseforge.com/minecraft/modpacks/verve-2). (You will not need to install the modpack itself, as it is an entirely server-sided issue.)
2. Run the server.
3. Execute "stop".
4. See error in console.

**Log output/error (if present)**

Stacktrace after executing "stop" command:
```
[19:12:21] [Server thread/ERROR] [ne.mi.fm.co.ConfigFileTypeHandler/]: Failed to remove config ./world/serverconfig/betteranimalsplus-server.toml from tracker!
java.lang.NullPointerException: null
        at com.electronwill.nightconfig.core.file.FileWatcher.removeWatch(FileWatcher.java:134) ~[core-3.6.2.jar:?] {}
        at net.minecraftforge.fml.config.ConfigFileTypeHandler.unload(ConfigFileTypeHandler.java:76) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.config.ConfigTracker.closeConfig(ConfigTracker.java:114) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.config.ConfigTracker.lambda$unloadConfigs$2(ConfigTracker.java:88) ~[forge:?] {re:classloading}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_282] {}
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2064) ~[?:1.8.0_282] {}
        at net.minecraftforge.fml.config.ConfigTracker.unloadConfigs(ConfigTracker.java:88) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:135) ~[forge:?] {re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:682) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}
```

[debug.log](https://gist.github.com/paulhlschr/838f64fcc106e75813921e903b026079)

**Expected behavior**
The server stops gracefully and returns to shell after saving the world.

**Versions:**
 - Minecraft Version: 1.16.4
 - Forge Version: 35.1.37
 - Mod Version: 1.16.4-10.1.0

**Additional context**
Modlist: https://www.curseforge.com/minecraft/modpacks/verve-2/relations/dependencies

This issue is very likely caused by an incompatibility with another mod or more specifically mixin.

**Comment by itsmeow** [comment]
So I've removed BAP from the pack and tried this again, and it happened with Astral Sorcery. I very much doubt this is an issue with our mod, but instead something else in the pack doing it for *all* mods. Ours just happened to go first.

**Comment by koderian** [comment]
I got the same issue

**Comment by paulhlschr** [comment]
> I got the same issue

@koderian May you provide a full modlist? Maybe we can find some similiarities.

**Comment by koderian** [comment]
Sure, yeah. Well basically, I have the same problem. When I stop my server it doesn't fully shut down and the process remains running until I force-kill it. Running Forge 1.16.5 latest (currently).  Here is the latest.log https://gist.github.com/koderian/14433d2abbffdc193eabc6b14148f373

And here is the modlist on the server: https://gist.github.com/koderian/6bedb7084329a850b1ece4f70b4cfb83

**Comment by itsmeow** [comment]
Ran a diffcheck with your modlists.
Not sure what could be causing this still.
https://www.diffchecker.com/EX9mcRYE

**Comment by itsmeow** [comment]
Do note the diff checker isn't perfect for mods and the same mods with different versions will show up as red/green so make sure to look at those closely. I'm not able to spend time investigating what every mod there does, but anything that messes with the internals of the game and maybe doesn't have a ton of DLs could be behind it.

**Comment by itsmeow** [comment]
I think it might be TerraForged, guys. Someone in my Discord has said that was causing the issue for them and both of your modlists include TerraForged.

**Comment by paulhlschr** [comment]
> I think it might be TerraForged, guys. Someone in my Discord has said that was causing the issue for them and both of your modlists include TerraForged.

Thank you for information. As far as I have tested it is not related to TerraForged tho. I am going to test a variety of combinations with my modpack using pivot. Maybe I have success to find one specific incompatible mod.

Also, thank you for giving us this issue as a discussion board. Others would have closed it by now already :D

**Comment by paulhlschr** [comment]
I have found the specific mod, that is causing this error and opened an issue on the relevant page. (Any reactions to it would be great to push it.)
Thank you very much for your time and help and I am sorry for the inconvenience I have caused, as BAP never was the problem.

Thank you for your mod, stay safe and healthy! :)

**Comment by itsmeow** [comment]
What mod was it, since I have had some people contact me about this through other channels?

**Comment by itsmeow** [comment]
Ah sorry, missed the issue mention there. Thanks!

**Comment by SaemonMoki** [comment]
Just as a head's up, we have fixed this issue in our latest release. So we (genetic animals), shouldn't be causing this error for your mod any longer. If it still remains an issue, let me know.
