### ISSUE TITLE
Virus? 🤔

### ISSUE THREAD

**Issue by TenDeeZedd** [itsmeow/betteranimalsplus#354]
It's been two days since I downloaded this mod. Everything was fine. I was still playing this morning. But now I won't turn on the game. After loading, the game crashes. It says it's because the file contains a virus or potentially unwanted software. After that the mod is automatically deleted. I tried to download new file from CurseForge but Windows Defender blocked it due to a virus.

I'm kinda confused. I tried to scan it with Eset and Malwarebytes and they say it's OK. After that Windows Defender says it's OK too... So now I can play normally... So I don't have problem... But maybe it can be somehow useful to you.

Mod version 1.19-11.0.6-fabric
Loader version: 0.14.8

Detected: Trojan:Script/Ulthar.A!ml

`Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:210)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\tende\AppData\Roaming\.minecraft\mods\betteranimalsplus-1.19-11.0.6-fabric.jar]: java.io.FileNotFoundException: C:\Users\tende\AppData\Roaming\.minecraft\mods\betteranimalsplus-1.19-11.0.6-fabric.jar (The operation was not completed successfully because the file contains a virus or potentially unwanted software)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:143)
	... 5 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\tende\AppData\Roaming\.minecraft\mods\betteranimalsplus-1.19-11.0.6-fabric.jar]: java.io.FileNotFoundException: C:\Users\tende\AppData\Roaming\.minecraft\mods\betteranimalsplus-1.19-11.0.6-fabric.jar (The operation was not completed successfully because the file contains a virus or potentially unwanted software)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:255)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.io.FileNotFoundException: C:\Users\tende\AppData\Roaming\.minecraft\mods\betteranimalsplus-1.19-11.0.6-fabric.jar (The operation was not completed successfully because the file contains a virus or potentially unwanted software)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1312)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:280)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:250)
	... 7 more
`

**Comment by itsmeow** [comment]
Please inform, where are you downloading the mod from?

**Comment by itsmeow** [comment]
No one else has had this problem, so I'm assuming your antivirus just went haywire or you somehow got it from a bad source.

**Comment by TenDeeZedd** [comment]
I downloaded it here [https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus/files](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus/files)
Detailed information from Win Defender
`webfile: C:\Users\tende\Downloads\betteranimalsplus-1.19-11.0.6-fabric.jar|https://mediafiles.forgecdn.net/files/3825/878/betteranimalsplus-1.19-11.0.6-fabric.jar|pid:14396,ProcessStart:133009191280487235`

As I said, I scanned it with Eset and Malwarebytes and it was ok. After 3 blocked files even Win Defender says it's ok. So yeah, Win Defender probably failed? Dunno... I wanted to share it if it could be useful in any way.
