### ISSUE TITLE
Mod fails to load

### ISSUE THREAD

**Issue by kruubipuder** [itsmeow/betteranimalsplus#356]
## Describe what you were doing before the crash

Loading game

## To Reproduce

Steps to reproduce the behavior (if possible):
1. Open Minecraft
2. Launch Minecraft with mods:
    - Alex's mobs
    - Aquaculture
    - Architectury
    - Better Animals Plus
    - Better Animals Models
    - Citadel
    - Curios
    - Exotic Birds
    - Waddles
    - Worldedit
4. Game opens saying Better Animals Plus has failed to load correctly (java.lang.reflect.InvocationTargetException: null)

## Crash Log (REQUIRED)

---- Minecraft Crash Report ----
// There are four lights!

Time: 7/15/22, 2:55 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.0.98-universal.jar%23158!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.0.98-universal.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:432) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixin.imdlib-betteranimalsplus.json:UtilMixin,pl:mixin:APP:mixin.imdlib-betteranimalmodels.json:UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23153!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.98.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.itsmeow.betteranimalsplus.imdlib.entity.util.forge.BiomeTypesImpl.init(BiomeTypesImpl.java:20) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23147!/:1.19-11.0.6] {re:classloading}
-- MOD betteranimalsplus --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.98.jar%23155!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.98.jar%23154!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: betteranimalsplus-1.19-11.0.6-forge.jar
	Failure message: Better Animals Plus (betteranimalsplus) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.19-11.0.6
	Mod Issue URL: https://github.com/itsmeow/betteranimalsplus/issues
	Exception message: java.lang.NoSuchFieldError: IS_SAVANNA
Stacktrace:
	at dev.itsmeow.betteranimalsplus.imdlib.entity.util.forge.BiomeTypesImpl.init(BiomeTypesImpl.java:20) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23147!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.imdlib.entity.util.BiomeTypes.init(BiomeTypes.java) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23147!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.imdlib.entity.util.BiomeTypes.<clinit>(BiomeTypes.java:81) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23147!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.init.ModEntities.lambda$static$1(ModEntities.java:61) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23147!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.util.EntityRegistrarHandlerBAP.addTame(EntityRegistrarHandlerBAP.java:20) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23147!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.init.ModEntities.<clinit>(ModEntities.java:47) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23147!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.BetterAnimalsPlusMod.construct(BetterAnimalsPlusMod.java:45) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23147!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.forge.BetterAnimalsPlusModForge.<init>(BetterAnimalsPlusModForge.java:27) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23147!/:1.19-11.0.6] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.98.jar%23155!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.98.jar%23154!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 483334480 bytes (460 MiB) / 761266176 bytes (726 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=30.0.15020.1001
	Graphics card #1 name: Radeon RX 560X
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x67ef
	Graphics card #1 versionInfo: DriverVersion=30.0.15020.1001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14273.94
	Virtual memory used (MB): 11664.59
	Swap memory total (MB): 6400.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		betteranimalsplus-1.19-11.0.6-forge.jar           |Better Animals Plus           |betteranimalsplus             |1.19-11.0.6         |ERROR     |Manifest: NOSIGNATURE
		forge-1.19-41.0.98-universal.jar                  |Forge                         |forge                         |41.0.98             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Aquaculture-1.19-2.4.4.jar                        |Aquaculture 2                 |aquaculture                   |1.19-2.4.4          |COMMON_SET|Manifest: NOSIGNATURE
		betteranimalmodels-1.19-5.6.0-forge.jar           |Cyber's Better Animal Models  |betteranimalmodels            |1.19-5.6.0          |COMMON_SET|Manifest: NOSIGNATURE
		worldedit-mod-7.2.11-beta-01.jar                  |WorldEdit                     |worldedit                     |7.2.11-beta-01+6200-|COMMON_SET|Manifest: NOSIGNATURE
		exoticbirds-1.19-2.2.0.jar                        |Exotic Birds                  |exoticbirds                   |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19-5.1.0.4.jar                     |Curios API                    |curios                        |1.19-5.1.0.4        |COMMON_SET|Manifest: NOSIGNATURE
		Waddles-1.19-0.9.1.jar                            |Waddles                       |waddles                       |1.19-0.9.1          |COMMON_SET|Manifest: NOSIGNATURE
		architectury-5.9.31-forge.jar                     |Architectury                  |architectury                  |5.9.31              |COMMON_SET|Manifest: NOSIGNATURE
		citadel-1.12.6-1.19.jar                           |Citadel                       |citadel                       |1.12.6              |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.19.3.jar                              |Alex's Mobs                   |alexsmobs                     |1.19.3              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 38069123-a7cc-4a45-a77b-bf57cf114dd0
	FML: 41.0
	Forge: net.minecraftforge:41.0.98
## Versions
- Minecraft Version: 1.19
- Architectury API Version: 5.9.31
- Platform (Forge/Fabric): Forge
- Forge Version: 41.0.98
- Fabric Loader Version:
- Fabric API Version:
- Mod Version: 11.0.6

## Additional context
Without Better Animals Plus Mod, it doesn't crash.
![BAP-error](https://user-images.githubusercontent.com/109319896/179121706-1a65dcfb-9076-4425-8075-cc37b781b3cc.JPG)

**Comment by itsmeow** [comment]
Fixed by 43498d14b2c8ed0e8cbc3987b584cba110c115d6
