### ISSUE TITLE
Better Animals Plus fails to load once java is launched (1.19 forge)

### ISSUE THREAD

**Issue by PowerOfDoggo** [itsmeow/betteranimalsplus#366]
I was launching java from the curseforge mc launcher and once it launches, I get an error.

## To Reproduce

Steps to reproduce the behavior (if possible):
1. ok ngl dont know what this means 💀 

## Crash Log (REQUIRED)

**Time: 8/10/22, 8:37 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.1.0-universal.jar%23160!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.1.0-universal.jar%23160!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:432) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixin.imdlib-betteranimalsplus.json:UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:IMixinGameRenderer,pl:mixin:APP:witherstormmod.mixins.json:MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone.mixins.json:client.MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23155!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.1.0.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.itsmeow.betteranimalsplus.imdlib.entity.util.forge.BiomeTypesImpl.init(BiomeTypesImpl.java:20) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23146!/:1.19-11.0.6] {re:classloading}
-- MOD betteranimalsplus --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23157!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23156!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /Users/panio/Documents/curseforge/minecraft/Instances/wyan/mods/betteranimalsplus-1.19-11.0.6-forge.jar
	Failure message: Better Animals Plus (betteranimalsplus) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.19-11.0.6
	Mod Issue URL: https://github.com/itsmeow/betteranimalsplus/issues
	Exception message: java.lang.NoSuchFieldError: IS_SAVANNA
Stacktrace:
	at dev.itsmeow.betteranimalsplus.imdlib.entity.util.forge.BiomeTypesImpl.init(BiomeTypesImpl.java:20) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23146!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.imdlib.entity.util.BiomeTypes.init(BiomeTypes.java) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23146!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.imdlib.entity.util.BiomeTypes.<clinit>(BiomeTypes.java:81) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23146!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.init.ModEntities.lambda$static$1(ModEntities.java:61) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23146!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.util.EntityRegistrarHandlerBAP.addTame(EntityRegistrarHandlerBAP.java:20) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23146!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.init.ModEntities.<clinit>(ModEntities.java:47) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23146!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.BetterAnimalsPlusMod.construct(BetterAnimalsPlusMod.java:45) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23146!/:1.19-11.0.6] {re:classloading}
	at dev.itsmeow.betteranimalsplus.forge.BetterAnimalsPlusModForge.<init>(BetterAnimalsPlusModForge.java:27) ~[betteranimalsplus-1.19-11.0.6-forge.jar%23146!/:1.19-11.0.6] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23157!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23156!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (aarch64) version 12.3.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 142648832 bytes (136 MiB) / 545259520 bytes (520 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 10240.00
	Virtual memory used (MB): 8311.44
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1361.75
	JVM Flags: 2 total; -Xmx4096m -Xms256m
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		witherstormmod-1.19-3.0-beta.jar                  |Cracker's Wither Storm Mod    |witherstormmod                |3.0-beta            |COMMON_SET|Manifest: NOSIGNATURE
		the_bumblezone_forge-6.1.7+1.19.jar               |The Bumblezone                |the_bumblezone                |6.1.7+1.19          |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19-2.0.0.119.jar             |TerraBlender                  |terrablender                  |2.0.0.119           |COMMON_SET|Manifest: NOSIGNATURE
		betteranimalsplus-1.19-11.0.6-forge.jar           |Better Animals Plus           |betteranimalsplus             |1.19-11.0.6         |ERROR     |Manifest: NOSIGNATURE
		forge-1.19-41.1.0-universal.jar                   |Forge                         |forge                         |41.1.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		BiomesOPlenty-1.19-17.0.0.143.jar                 |Biomes O' Plenty              |biomesoplenty                 |17.0.0.143          |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_22.12.0_Forge_1.19.jar             |Xaero's Minimap               |xaerominimap                  |22.12.0             |COMMON_SET|Manifest: NOSIGNATURE
		gravestone-1.19-1.0.3.jar                         |Gravestone Mod                |gravestone                    |1.19-1.0.3          |COMMON_SET|Manifest: NOSIGNATURE
		architectury-5.11.40-forge.jar                    |Architectury                  |architectury                  |5.11.40             |COMMON_SET|Manifest: NOSIGNATURE
		bedspreads-forge-6.0.0-beta.2+1.19.jar            |Bedspreads                    |bedspreads                    |6.0.0-beta.2+1.19   |COMMON_SET|Manifest: NOSIGNATURE
		TravelersBackpack-1.19-8.0.8.jar                  |Traveler's Backpack           |travelersbackpack             |8.0.8               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 6de403b0-3f6c-4ea1-9333-293a1cd9ab9e
	FML: 41.1
	Forge: net.minecraftforge:41.1.0**

## Versions
- Minecraft Version:
- Architectury API Version: Forge
- Platform (Forge/Fabric): Forge
- Forge Version: 1.19
- Fabric Loader Version: 41.1.0
- Fabric API Version: uh forge?
- Mod Version: 1.19

## Additional context

I'm using a macbook btw... dont really know what else to put here sry.

**Comment by itsmeow** [comment]
11.0.7 fixed this
