### ISSUE TITLE
Bug - error on load - 1.19.3

### ISSUE THREAD

**Issue by SleepyCatten** [itsmeow/betteranimalsplus#383]
## Describe the bug
Does not work with 1.19.3

## To Reproduce
1. Set up a Fabric server based on Minecraft 1.19.3
2. Copy the mod & its dependencies into the mods folder.
3. Start the server.

## Log output/error (if present)
[16:42:47] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[16:42:47] [main/WARN]: Mod resolution failed
[16:42:47] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED betteranimalsplus 1.19.2-11.0.9 {depends minecraft @ [1.19.2]}, ROOT_FORCELOAD_SINGLE betteranimalsplus 1.19.2-11.0.9]
[16:42:47] [main/INFO]: Reason: [HARD_DEP betteranimalsplus 1.19.2-11.0.9 {depends minecraft @ [1.19.2]}]
[16:42:47] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, modmenu, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, fabric-renderer-registries-v1, fabric-models-v0, fabric-sound-api-v1, fabric-rendering-v0, fabric-key-binding-api-v1, fabric-rendering-v1]
[16:42:47] [main/INFO]: Fix: add [], remove [], replace [[betteranimalsplus 1.19.2-11.0.9] -> add:betteranimalsplus 1 ([(-∞,∞)])]
[16:42:47] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Better Animals Plus' (betteranimalsplus) 1.19.2-11.0.9 with any version that is compatible with:
		 - minecraft 1.19.3
Unmet dependency listing:
	 - Mod 'Better Animals Plus' (betteranimalsplus) 1.19.2-11.0.9 requires version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.1]

## Expected behavior
Should load up.

## Screenshots
N/A

## Versions
 - Minecraft Version: 1.19.3
 - Architectury API Version: 7.0.66-fabric
 - Platform (Forge/Fabric): Fabric 
 - Forge Version:
 - Fabric Loader Version: 0.14.12
 - Fabric API Version: 0.70.0+1.19.3
 - Mod Version: 1.19.2-11.0.9-fabric

## Additional context
Probably just needs a quick edit to tell the mod that it's compatible with 1.19.3

**Comment by itsmeow** [comment]
It's not compatible with 1.19.3
