### ISSUE TITLE
Crash on death using the latest [FIXED] version on a forge server

### ISSUE THREAD

**Issue by Stefanowhb** [itsmeow/betteranimalsplus#92]
1. Spawn
2. Die
3. See error

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 9/14/19 12:43 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.getPersistantData()Lnet/minecraft/nbt/CompoundNBT;
	at its_meow.betteranimalsplus.common.CommonEventHandler.onPlayerRespawn(CommonEventHandler.java:134) ~[?:7.1.1] {}
	at net.minecraftforge.eventbus.ASMEventHandler_94_CommonEventHandler_onPlayerRespawn_Clone.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:462) ~[?:?] {}
	at net.minecraft.entity.player.ServerPlayerEntity.func_193104_a(ServerPlayerEntity.java:1041) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.management.PlayerList.func_72368_a(PlayerList.java:404) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:1097) ~[?:?] {}
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:31) ~[?:?] {}
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}

```

**Comment by itsmeow** [comment]
Known issue, new RB has another rename of the same method. Simple fix but I've been fairly busy. If you really need to use the mod you can use a version between 28.0.92 to the RB (excluding RB)
